{% set name = "jemalloc" %}
{% set version = "5.2.1" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://github.com/jemalloc/jemalloc/releases/download/{{ version }}/jemalloc-{{ version }}.tar.bz2
  sha256: 34330e5ce276099e2e8950d9335db5a875689a4c6a56751ef3b1d8c537f887f6
  patches:
    - export-mangled-syms.patch

build:
  number: 6
  skip: true  # [win]

outputs:
  - name: libjemalloc
    script: build-jemalloc.sh
    build:
      run_exports:
        # Symbols were only removed in update from 3 to 4
        # https://abi-laboratory.pro/index.php?view=timeline&l=jemalloc
        - {{ pin_subpackage('libjemalloc', max_pin=None) }}
    requirements:
      build:
        - make
        - gnuconfig  # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
    test:
      commands:
        - test -f $PREFIX/lib/libjemalloc.so.2  # [linux]
        - test ! -f $PREFIX/lib/libjemalloc.a
        - test ! -f $PREFIX/lib/libjemalloc_pic.a
        - test ! -f $PREFIX/bin/jeprof
        - test -f $PREFIX/lib/libjemalloc.2.dylib  # [osx]
        - test -f $PREFIX/include/jemalloc/jemalloc.h

  - name: {{ name }}
    script: build-jemalloc.sh
    build:
      run_exports:
        # Symbols were only removed in update from 3 to 4
        # https://abi-laboratory.pro/index.php?view=timeline&l=jemalloc
        - {{ pin_subpackage('libjemalloc', max_pin=None) }}
    requirements:
      build:
        - make
        - gnuconfig  # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('libjemalloc', exact=true) }}
      run:
        - {{ pin_subpackage('libjemalloc', exact=true) }}
    test:
      requires:
        - {{ compiler('c') }}
      files:
        - test.c
      commands:
        - test -f $PREFIX/bin/jeprof
        - $CC -I$PREFIX/include -L$PREFIX/lib -ljemalloc test.c

  - name: lib{{ name }}-local
    script: build-jemalloc-local.sh
    build:
      run_exports:
        # Symbols were only removed in update from 3 to 4
        # https://abi-laboratory.pro/index.php?view=timeline&l=jemalloc
        - {{ pin_subpackage("libjemalloc-local", max_pin=None) }}
    requirements:
      build:
        - make
        - gnuconfig  # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
    test:
      commands:
        - test -f $PREFIX/lib/libjemalloclocal.so.2  # [linux]
        - test ! -f $PREFIX/lib/libjemalloc${SHLIB_EXT}
        - test ! -f $PREFIX/lib/libjemalloclocal.a
        - test ! -f $PREFIX/lib/libjemalloclocal_pic.a
        - test -f $PREFIX/lib/libjemalloclocal.2.dylib  # [osx]
        - test -f $PREFIX/include/jemalloc/jemalloclocal.h
        - test ! -f $PREFIX/jeprof

  - name: {{ name }}-local
    script: build-jemalloc-local.sh
    build:
      run_exports:
        # Symbols were only removed in update from 3 to 4
        # https://abi-laboratory.pro/index.php?view=timeline&l=jemalloc
        - {{ pin_subpackage("libjemalloc-local", max_pin=None) }}
    requirements:
      build:
        - make
        - gnuconfig  # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('libjemalloc-local', exact=true) }}
      run:
        - {{ pin_subpackage('libjemalloc-local', exact=true) }}
      run_constrained:
        - jemalloc <0a0
    test:
      requires:
        - {{ compiler('c') }}
      files:
        - test-local.c
      commands:
        - test -f $PREFIX/bin/jeprof
        - $CC -I$PREFIX/include -L$PREFIX/lib -ljemalloclocal test-local.c

about:
  home: http://jemalloc.net
  dev_url: https://github.com/jemalloc/jemalloc
  license: BSD-2-Clause
  license_file: COPYING
  summary: 'general purpose malloc(3) implementation'

extra:
  feedstock-name: jemalloc
  recipe-maintainers:
    - wesm
    - xhochy
